name: Deploy My Portfolio Website to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-site:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout Code
        uses: actions/checkout@v4

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build Project
        run: npm run build

      # Optional: save build output as artifact so deploy job can use it
      - name: 📁 Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  deploy:
    name: 🚀 Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build-site  # ✅ This must be at the job level
    steps:
      - name: 🛠️ Checkout Code
        uses: actions/checkout@v4

      - name: 📥 Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: 📦 Install Vercel CLI
        run: npm install -g vercel

      - name: 🚀 Deploy to Vercel
        run: vercel --token=${{ secrets.portfolio_token }} --prod --yes
